# Kernels

If we think of an image as a big matrix, then we can think of a kernel or convolutional matrix as a tiny matrix that is used for 
* blurring, 
* sharpening, 
* edge detection, 
* and other image processing functions.

This tiny kernel sits on top of the big image and slides from left to right and up to down, applying a mathematical operation at each (x, y)-coordinate in the original image.

![](images/lec05.png)

**Let's apply a kernel to an image (via convolution) on the whiteboard.**

* Kernels: http://slides.com/jaytrivedi/deck#/45
* Kernels in CNN: http://slides.com/jaytrivedi/deck#/61
* Visualizing Convolution: http://setosa.io/ev/image-kernels/

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
img = cv2.imread('./images/face001.jpg')
rows, cols = img.shape[:2]

In [4]:
rows

422

In [5]:
cols

759

Putting it all together:

In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

img = cv2.imread('../assets/images/face001.jpg')
rows, cols = img.shape[:2]

def plot_img(img):
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img_rgb)
    plt.xticks([])
    plt.yticks([])
    plt.show()
    return None

def kernel_tranform(img, kernel):
    output = cv2.filter2D(img, -1, kernel)
    plot_img(output)
    return None
    

In [ ]:
plot_img(img)

# Idempotent

In [15]:
kernel_0 = np.array([[0,0,0], 
                     [0,1,0], 
                     [0,0,0]])
kernel_0

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [ ]:
kernel_tranform(img, kernel_0)

# Blurring

In [16]:
kernel_1 = np.array([[1,1,1],
                     [1,1,1],
                     [1,1,1]])/9
kernel_1

array([[ 0.11111111,  0.11111111,  0.11111111],
       [ 0.11111111,  0.11111111,  0.11111111],
       [ 0.11111111,  0.11111111,  0.11111111]])

In [ ]:
kernel_tranform(img, kernel_1)

## More Blurring

In [26]:
kernel_2 = np.ones((5,5), np.float32) / 25.0
kernel_2

array([[ 0.04,  0.04,  0.04,  0.04,  0.04],
       [ 0.04,  0.04,  0.04,  0.04,  0.04],
       [ 0.04,  0.04,  0.04,  0.04,  0.04],
       [ 0.04,  0.04,  0.04,  0.04,  0.04],
       [ 0.04,  0.04,  0.04,  0.04,  0.04]], dtype=float32)

In [ ]:
kernel_tranform(img, kernel_2)

## Even more Blurring

In [ ]:
kernel_3 = np.ones((7,7), np.float32) / 49.0
kernel_3

In [ ]:
kernel_tranform(img, kernel_3)

# Sobel

In [ ]:
kernel_Sx = np.array([[-1,0,1], 
                      [-2,0,2], 
                      [-1,0,1]])
kernel_Sy = np.array([[-1,-2,-1], 
                      [0,0,0], 
                      [1,2,1]])

In [ ]:
kernel_Sx

In [ ]:
kernel_Sy

In [ ]:
kernel_tranform(img, kernel_Sx)

In [ ]:
kernel_tranform(img, kernel_Sy)